org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.disableProjectDependentMods = true

display_name=SOL: Valheim Continued
archives_base_name=sol_valheim
modid = sol_valheim

curseforge_id = 962299
modrinth_id = mKalCkNV

mod_version=1.0.0-pre.1
maven_group=vice

# the mc version to compile against (see their respective property files for version-specific stuff)
mcVer=1.20.1

# which versions to put in the build.properties file
mc_versions=1.19.2, 1.20.1, 1.21.1

# which version to use if mcVer is invalid/not in mc_versions
default_mc_version=1.19.2

# probably dont need to touch this
enabled_platforms=fabric, forge

# Whether or not to make a jar that works for both Fabric and Forge
merge_jars = false

# Gradle Plugin Versions
arch_plugin_version = 3.5.169
loom_version = 1.14.476
shadow_version = 8.3.11
forgix_version = 2.0.0
machete_version = 2.0.1

manifold_version = 2026.1.12
